### ISSUE TITLE
Vidéo tuto + Tournoi

### ISSUE THREAD

**Issue by tocarpenti** [tocarpenti/Algorithm-101#2]
- Vidéo du tuto (2min)
- Speech de présentation (3min)

**Comment by ExcelSior22** [comment]
La video tuto:
Dans la presentation de notre projet dans le stand, on a decider faire une video tuto qui tourne en boucle, qui vq permettre au gens qui passent a cote du stand puisse comprendre et ainsi etrs intersse a notre jeux, une video de 2 min est largement suffisante pour se genre de jeux.
Presentation du jeux,
Presentation de l'interface,
Resoudre un petit probleme de programation (exemple de la condition if: 2 bon hommes programmer le premier pour s'arreter a une case qui va permettre au deuxieme d'ouvrir la porte et ainsi passer au niveau suvant).

Speech de presentation:
Mohammed -> L'algorithme 101 comme son nom l'indique est un jeu algorithmique qui a pour but d'initier la personne aux notions élémentaires de l'algorithme.
L’intérêt de ce jeu est que n'importe quelle personne peut y jouer, qu'il soit adulte ou enfant (intéressée par l'algorithme ou pas).
Comment jouer ?
le principe est simple, il consiste à faire entrer une série d'instruction sur les touches d'une borne d’arcade (par exemple) pour pouvoir sortir son bonhomme d'un labyrinthe. L’utilisateur ne verra pas tout de suite le résultat de ces instructions, il devra d'abord faire entrer sa série d'instruction puis confirmé ses instructions et c'est seulement une fois qu'il aura confirmé qu'il verra le résultat de ces instructions (réussi ou pas) et recommencer si nécessaire.

**Comment by ExcelSior22** [comment]
Tournoi :
Ce jeu peut etres incruste dans tous les colleges, lycees puisqu'il est simple et permet l'initiation des gens au monde de la programmation, on pourrai organiser alors des tournois local dans les colleges lycees, regionnal et pourquoi pas natianol si les jeunnes apprecient le jeu.
Le but etant de diffuser au plus le jeu entres les jeunnes.
