### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by tocarpenti** [tocarpenti/Algorithm-101#3]
- Améliorer le logo
- Faire le design 3d de la borne

**Comment by Chihab-loughlimi** [comment]
![salle jeux@0 25x](https://user-images.githubusercontent.com/17486030/151705416-bf63d7fd-8bf5-4a93-b09c-6552b3ec86dd.png)
![accueil@0 25x](https://user-images.githubusercontent.com/17486030/151705420-e61d6dd9-4df0-48ef-903b-fd6450b6cffa.png)
![LOGOS](https://user-images.githubusercontent.com/17486030/151705421-d8427f57-4a62-42b3-9010-2da9e45d66df.png)
![LOGOSw](https://user-images.githubusercontent.com/17486030/151705422-88d63f58-c472-4157-93b0-614508b80ae5.png)
