### ISSUE TITLE
Test des joueurs

### ISSUE THREAD

**Issue by tocarpenti** [tocarpenti/Algorithm-101#4]
Signaler aux animateurs qu'ils doivent aider les joueurs en difficultés et leurs expliquer les énigmes et les concepts associés.

**Comment by Moustapha27** [comment]
Test des joueurs

Après avoir fait notre speech de présentation il serait bien  de faire passé des tests a nos participants. Pour cela chaque joueur(participant) aura droit a un test de 15 a 20 minutes maximum pour découvrir le jeu et ça sera une sorte de compétition entre les différents participants d'où le vainqueur aura droit a un prix. A la fin des ces quelques minutes de compétition, il est possible de continuer le jeu chez sois  en téléchargeant sur son smartphone si ce dernier l'intéresse bien sur.
Et durant la compétition un des organisateurs pourra intervenir si nécessaire pour un joueur qui reste bloqué plus de 5 minutes sur un énigme histoires de fluidifier la compétition.
